package router

import (
	"encoding/json"
	"net/http"
	"net/url"
	"strings"

	_ "github.com/Dragodui/diploma-server/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/Dragodui/diploma-server/internal/config"
	"github.com/Dragodui/diploma-server/internal/http/handlers"
	"github.com/Dragodui/diploma-server/internal/http/middleware"
	ratelimiter "github.com/Dragodui/diploma-server/internal/http/rate_limiter"
	ws "github.com/Dragodui/diploma-server/internal/http/websocket"
	"github.com/Dragodui/diploma-server/internal/repository"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/cors"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/redis/go-redis/v9"
	httpSwagger "github.com/swaggo/http-swagger"
)

type RoutesDeps struct {
	Config   *config.Config
	Handlers HandlerSet
	Cache    *redis.Client
	HomeRepo repository.HomeRepository
}

type HandlerSet struct {
	Auth         *handlers.AuthHandler
	Home         *handlers.HomeHandler
	Task         *handlers.TaskHandler
	TaskSchedule *handlers.TaskScheduleHandler
	Bill         *handlers.BillHandler
	BillCategory *handlers.BillCategoryHandler
	Room         *handlers.RoomHandler
	Shopping     *handlers.ShoppingHandler
	Image        *handlers.ImageHandler
	Poll         *handlers.PollHandler
	Notification *handlers.NotificationHandler
	Audit        *handlers.AuditHandler
	User         *handlers.UserHandler
	OCR          *handlers.OCRHandler
	SmartHome    *handlers.SmartHomeHandler
	PushSub      *handlers.PushSubscriptionHandler
	Note         *handlers.NoteHandler
}

// SetupRoutes configures all application routes.
func SetupRoutes(deps RoutesDeps) http.Handler {
	cfg := deps.Config
	cache := deps.Cache
	homeRepo := deps.HomeRepo
	authHandler := deps.Handlers.Auth
	homeHandler := deps.Handlers.Home
	imageHandler := deps.Handlers.Image
	notificationHandler := deps.Handlers.Notification
	auditHandler := deps.Handlers.Audit
	userHandler := deps.Handlers.User
	ocrHandler := deps.Handlers.OCR
	pushSubHandler := deps.Handlers.PushSub

	// websockets handler for real time updates
	wsHandler := ws.NewWSHandler(cfg, homeRepo)
	// Rate limiter
	rateLimiter := ratelimiter.NewIpRateLimiter()

	r := chi.NewRouter()
	// Request body size limit - prevents DoS via huge payloads
	r.Use(middleware.BodySizeLimit)
	// CORS middleware
	r.Use(cors.Handler(cors.Options{
		AllowedOrigins:   corsAllowedOrigins(cfg),
		AllowedMethods:   []string{"GET", "POST", "DELETE", "PATCH", "PUT", "OPTIONS"},
		AllowedHeaders:   []string{"Authorization", "Content-Type"},
		ExposedHeaders:   []string{"Content-Length"},
		AllowCredentials: true,
		MaxAge:           300,
	}))
	// Security headers middleware
	r.Use(middleware.SecurityHeadersWithHSTS(cfg.Mode != "dev"))

	// Public healthcheck
	r.Get("/", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusAccepted)
		json.NewEncoder(w).Encode("OK")
	})

	r.Get("/ws", func(w http.ResponseWriter, r *http.Request) {
		wsHandler.HandleWS(w, r, cache)
	})
	r.Group(func(r chi.Router) {
		// Global rate limiter - 120 requests per minute
		r.Use(middleware.RateLimitMiddleware(rateLimiter))

		r.Use(middleware.MetricsMiddleware)
		// HTTP request logger
		r.Use(middleware.RequestResponseLogger)
		// Protected admin endpoints (Prometheus metrics and Swagger docs)
		// Requires Basic Authentication
		r.Group(func(r chi.Router) {
			r.Use(middleware.BasicAuth(cfg.AdminUsername, cfg.AdminPassword))

			// Prometheus metrics - requires auth
			r.Handle("/metrics", promhttp.Handler())

			// Swagger UI - requires auth
			r.Get("/swagger/*", httpSwagger.WrapHandler)
		})

		// API routes
		r.Route("/api", func(r chi.Router) {
			// Auth routes (no JWT required) - with strict rate limiting
			r.Route("/auth", func(r chi.Router) {
				// Strict rate limit for login/register: 5 requests per minute
				authStrictLimit := middleware.StrictRateLimitMiddleware(rateLimiter, 5, 0.083) // 5 tokens, refill 0.083/sec = 5/min

				r.With(authStrictLimit).Post("/register", authHandler.Register)
				r.With(authStrictLimit).Post("/login", authHandler.Login)
				r.With(authStrictLimit).Post("/google/mobile", authHandler.GoogleSignIn)

				// OAuth endpoints - moderate limit
				r.Get("/{provider}", authHandler.SignInWithProvider)
				r.Get("/{provider}/callback", authHandler.CallbackHandler)

				// Email verification - no limit for verify (one-time use token)
				r.Get("/verify", authHandler.VerifyEmail)

				// Email verification regenerate - strict limit: 3 requests per 5 minutes (prevents spam)
				verifyRegenerateLimit := middleware.StrictRateLimitMiddleware(rateLimiter, 3, 0.01) // 3 tokens, refill 0.01/sec = 0.6/min
				r.With(verifyRegenerateLimit).Get("/verify/regenerate", authHandler.RegenerateVerify)

				// Password reset - very strict: 3 requests per 5 minutes
				resetStrictLimit := middleware.StrictRateLimitMiddleware(rateLimiter, 3, 0.01) // 3 tokens, refill 0.01/sec = 0.6/min
				r.With(resetStrictLimit).Post("/forgot", authHandler.ForgotPassword)
				r.With(resetStrictLimit).Post("/reset", authHandler.ResetPassword)
			})

			// Protected routes
			r.Group(func(r chi.Router) {
				// JWT authentication for all following routes
				r.Use(middleware.JWTAuth([]byte(cfg.JWTSecret), cache))

				// Change password (authenticated)
				changePasswordLimit := middleware.StrictRateLimitMiddleware(rateLimiter, 5, 0.083)
				r.With(changePasswordLimit).Post("/auth/change-password", authHandler.ChangePassword)

				// Logout (authenticated)
				r.Post("/auth/logout", authHandler.Logout)

				r.Get("/audit/my", auditHandler.GetMyEvents)

				// User routes
				r.Post("/user", userHandler.GetMe)
				r.Patch("/user", userHandler.Update)

				// Upload images - limited to 10 per minute
				uploadLimit := middleware.StrictRateLimitMiddleware(rateLimiter, 10, 0.167) // 10 tokens, refill 0.167/sec = 10/min
				r.With(uploadLimit).Post("/upload", imageHandler.UploadImage)

				// OCR processing - limited to 5 per minute (resource intensive)
				ocrLimit := middleware.StrictRateLimitMiddleware(rateLimiter, 5, 0.083) // 5 tokens, refill 0.083/sec = 5/min
				r.With(ocrLimit).Post("/ocr/process", ocrHandler.Process)

				// Push subscription endpoints
				r.Post("/notifications/subscribe", pushSubHandler.Subscribe)
				r.Get("/notifications/public_key", pushSubHandler.GetPublicKey)

				// Homes and nested resources
				r.Route("/homes", func(r chi.Router) {
					r.Post("/create", homeHandler.Create)    // Create home
					r.Post("/join", homeHandler.Join)        // Join home
					r.Get("/my", homeHandler.GetUserHome)    // Get user home (single)
					r.Get("/list", homeHandler.GetUserHomes) // Get all user homes

					// Notifications for user
					r.Route("/notifications", func(r chi.Router) {
						r.Get("/", notificationHandler.GetByUserID)
						r.Delete("/{notification_id}", notificationHandler.MarkAsRead)
					})

					// Home-specific actions
					r.Route("/{home_id}", func(r chi.Router) {
						r.With(middleware.RequireMember(homeRepo)).Get("/", homeHandler.GetByID)
						r.With(middleware.RequireAdmin(homeRepo)).Delete("/", homeHandler.Delete)
						r.With(middleware.RequireAdmin(homeRepo)).Patch("/", homeHandler.UpdateHome)
						r.With(middleware.RequireMember(homeRepo)).Post("/leave", homeHandler.Leave)
						r.With(middleware.RequireMember(homeRepo)).Get("/members", homeHandler.GetMembers)
						r.With(middleware.RequireAdmin(homeRepo)).Delete("/members/{user_id}", homeHandler.RemoveMember)
						r.With(middleware.RequireAdmin(homeRepo)).Get("/pending-members", homeHandler.GetPendingMembers)
						r.With(middleware.RequireAdmin(homeRepo)).Post("/members/{user_id}/approve", homeHandler.ApproveMember)
						r.With(middleware.RequireAdmin(homeRepo)).Post("/members/{user_id}/reject", homeHandler.RejectMember)
						r.With(middleware.RequireAdmin(homeRepo)).Patch("/members/{user_id}/role", homeHandler.UpdateMemberRole)
						r.With(middleware.RequireAdmin(homeRepo)).Post("/regenerate_code", homeHandler.RegenerateInviteCode)
						r.With(middleware.RequireAdmin(homeRepo)).Get("/audit", auditHandler.GetByHomeID)

						// Notifications for home
						r.Route("/notifications", func(r chi.Router) {
							mountHomeNotificationRoutes(r, deps)
						})

						// Rooms under a home
						r.Route("/rooms", func(r chi.Router) {
							mountRoomRoutes(r, deps)
						})

						// Tasks under a home
						r.Route("/tasks", func(r chi.Router) {
							mountTaskRoutes(r, deps)
						})

						// User assignments (not scoped to a specific home)
						r.Route("/users/{user_id}/assignments", func(r chi.Router) {
							mountUserAssignmentRoutes(r, deps)
						})

						// Bills under a home
						r.Route("/bills", func(r chi.Router) {
							mountBillRoutes(r, deps)
						})

						// Bill Categories
						r.Route("/bill_categories", func(r chi.Router) {
							mountBillCategoryRoutes(r, deps)
						})

						// Shopping
						r.Route("/shopping", func(r chi.Router) {
							mountShoppingRoutes(r, deps)
						})
						r.Route("/polls", func(r chi.Router) {
							mountPollRoutes(r, deps)
						})

						// Notes
						r.Route("/notes", func(r chi.Router) {
							mountNoteRoutes(r, deps)
						})

						// Note Categories
						r.Route("/note_categories", func(r chi.Router) {
							mountNoteCategoryRoutes(r, deps)
						})

						// Smart Home (Home Assistant integration)
						r.Route("/smarthome", func(r chi.Router) {
							mountSmartHomeRoutes(r, deps, rateLimiter, homeRepo)
						})
					})
				})
			})
		})
	})

	return r
}

func corsAllowedOrigins(cfg *config.Config) []string {
	origins := make([]string, 0, 8)
	seen := make(map[string]struct{})

	addOrigin := func(raw string) {
		origin := normalizeOrigin(raw)
		if origin == "" {
			return
		}
		if _, ok := seen[origin]; ok {
			return
		}
		seen[origin] = struct{}{}
		origins = append(origins, origin)
	}

	addOrigin(cfg.ClientURL)
	addOrigin(cfg.WebURL)

	if strings.EqualFold(cfg.Mode, "dev") {
		for _, origin := range []string{
			"http://localhost:3000",
			"http://localhost:5173",
			"http://localhost:8081",
			"http://127.0.0.1:3000",
			"http://127.0.0.1:5173",
			"http://127.0.0.1:8081",
		} {
			addOrigin(origin)
		}
	}

	return origins
}

func normalizeOrigin(raw string) string {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return ""
	}

	parsed, err := url.Parse(raw)
	if err != nil || parsed.Scheme == "" || parsed.Host == "" {
		return ""
	}

	switch parsed.Scheme {
	case "http", "https":
	default:
		return ""
	}

	return strings.TrimRight(parsed.Scheme+"://"+parsed.Host, "/")
}
